wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.6.2
    cli_version: 0.15.11
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699373321.515395
    t:
      1:
      - 55
      3:
      - 13
      - 23
      4: 3.6.2
      5: 0.15.11
      8:
      - 3
      - 5
      13: windows-amd64
