wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
momentum:
  desc: null
  value: 0.2
architecture:
  desc: null
  value: CNN
dataset_id:
  desc: null
  value: peds-0192
infra:
  desc: null
  value: AWS
_wandb:
  desc: null
  value:
    python_version: 3.6.2
    cli_version: 0.15.11
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699374395.351357
    t:
      1:
      - 55
      3:
      - 15
      - 16
      - 23
      4: 3.6.2
      5: 0.15.11
      8:
      - 3
      - 5
      13: windows-amd64
